version: "2"

networks:
  stockportfolio:
    driver: bridge

services:
  db:
    image: postgres:11
    container_name: stockportfolio_postgres
    restart: "always"
    ports:
      - "127.0.0.1:5439:5432"
    networks: ["stockportfolio"]
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stockportfolio
